alertmanagerFiles:
  alertmanager.yml:
    receivers:
      - name: default-receiver
        slack_configs:
         - channel: '#prod_alerts'
           send_resolved: true
           username: AlertBot
           title: |-
            {{ if eq .Status "firing" }}ERROR{{ else }}RESOLVED{{ end }}: 
              {{- range .Alerts }}{{ .Annotations.summary }}
            {{ end }}
           text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
      - name: warning-receiver
        slack_configs:
         - channel: '#prod_alerts'
           send_resolved: true
           username: AlertBot
           color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
           title: |-
            {{ if eq .Status "firing" }}WARNING{{ else }}RESOLVED{{ end }}: 
              {{- range .Alerts }}{{ .Annotations.summary }}
            {{ end }}
           text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    route:
      receiver: default-receiver
      # All alerts that do not match the following child routes
      # will remain at the root node and be dispatched to 'default-receiver'.
      routes:
        - receiver: warning-receiver
          match:
            severity: warning