apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: joomler-test
spec:
  schedule: "0 0 */1 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: callout
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl --silent --fail --max-redirs 1000 "https://staging-os-public-data.s3-us-west-2.amazonaws.com/joomler-test"