# I would like the below config to look like this, but you can't template values.
# Not sure how to accomplish this goal, particularly since `extraScrapeConfigs` expects a string.
#
# blackbox:
#   targets: #Add sites to monitor here
#     - https://cota.dev.internal.smartcolumbusos.com
#     - https://streaming.dev.internal.smartcolumbusos.com/socket/healthcheck
#   hostname: prometheus-prometheus-blackbox-exporter:9115

extraScrapeConfigs: |
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets: # Add sites to monitor here
        - https://cota.dev.internal.smartcolumbusos.com
        - https://streams.dev.internal.smartcolumbusos.com/socket/healthcheck
        - https://www.dev-smartos.com
        - https://discovery.dev.internal.smartcolumbusos.com
        - https://data.dev.internal.smartcolumbusos.com/healthcheck
        - https://parking.dev-smartos.com/api/v1/predictions 

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # ${namespace}-prometheus-blackbox-exporter:9115
        replacement: prometheus-prometheus-blackbox-exporter:9115

