extraScrapeConfigs: |
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets: # Add sites to monitor here
        - https://jupyter.smartcolumbusos.com/hub/login
        - https://cota.smartcolumbusos.com
        - https://streaming.smartcolumbusos.com/socket/healthcheck
        - https://ckan.smartcolumbusos.com/
        - https://www.smartcolumbusos.com/
        - https://survey.smartcolumbusos.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # ${namespace}-prometheus-blackbox-exporter:9115
        replacement: prometheus-prometheus-blackbox-exporter:9115
