{{- if (empty .Values.server.configMapOverrideName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.server.fullname" . }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.serverFiles }}
  {{ $key }}: |
{{- if eq $key "prometheus.yml" }}
    global:
{{ $root.Values.server.global | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{ toYaml $value | default "{}" | indent 4 -}}
{{- if eq $key "alerts" -}}
    - name: dataset_alerts
      rules:
      {{- range $.Values.datasetAlerts }}
      - alert: {{ .title | title | nospace }}
        expr: 'sum(rate(kafka_topic_partition_current_offset{topic="transformed-{{ .id }}"}[{{ .interval }}])) by (topic) == 0'
        labels:
          severity: error
        annotations:
          description: '{{ .title }} has not had any input in the last {{ .interval }}. ID: {{ .id }}'
          summary: 'The latest {{ .title }} data has not loaded'
      {{- end }}
    - name: consumer_group_lag_alerts
      rules:
      {{- range $.Values.consumerGroupLagAlerts }}
      - alert: {{ .alert }}
        expr: label_replace(label_replace(label_replace(sum(kafka_consumergroup_lag{{ .topic }}) by (consumergroup, topic, dataset) > {{ int .lag_limit }}, "dataset_id", "$3", "consumergroup", "(.+)-(raw|transformed)-(.*)"), "stage", "$2", "consumergroup", "(.+)-(raw|transformed)-(.*)"), "app", "$1", "consumergroup", "(.+)-(raw|transformed)-(.*)") * on (dataset_id) group_left(dataset_title, source_type, org_name) dataset_info_gauge
        labels:
          severity: warning
        annotations:
          description: 'Consumer Group lag topic {{ "{{" }} $labels.dataset_title }} has become {{ "{{" }} humanize $value }}.'
          summary: 'Consumer Group lag is greater than {{ .lag_limit }}'
      {{- end }}
{{- end }}
{{- if eq $key "prometheus.yml" -}}
{{- if $root.Values.extraScrapeConfigs }}
{{ tpl $root.Values.extraScrapeConfigs $root | indent 4 }}
{{- end -}}
{{- if $root.Values.alertmanager.enabled }}
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        {{- if $root.Values.alertmanager.prefixURL }}
        path_prefix: {{ $root.Values.alertmanager.prefixURL }}
        {{- end }}
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: {{ $root.Release.Namespace }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: prometheus
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_component]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
          action: drop
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
